// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: Hall.proto

package msg

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

///登陆类型
type C2S_Login_E_LoginType int32

const (
	///微信登陆
	C2S_Login_E_LoginType_WeChat C2S_Login_E_LoginType = 0
	///游客登陆
	C2S_Login_E_LoginType_Guest C2S_Login_E_LoginType = 1
)

var C2S_Login_E_LoginType_name = map[int32]string{
	0: "E_LoginType_WeChat",
	1: "E_LoginType_Guest",
}

var C2S_Login_E_LoginType_value = map[string]int32{
	"E_LoginType_WeChat": 0,
	"E_LoginType_Guest":  1,
}

func (x C2S_Login_E_LoginType) String() string {
	return proto.EnumName(C2S_Login_E_LoginType_name, int32(x))
}

func (C2S_Login_E_LoginType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_a77d98885c0f92eb, []int{0, 0}
}

type S2C_Login_E_ErrReason int32

const (
	///保留
	S2C_Login_E_ErrReason_ S2C_Login_E_ErrReason = 0
	///成功登陆,将下发数据
	S2C_Login_E_Err_LoginSuccess S2C_Login_E_ErrReason = 1
	///成功创建新账号,读表获取初始数据
	S2C_Login_E_Err_NewAccount S2C_Login_E_ErrReason = 2
	///登陆信息不匹配,登陆失败
	S2C_Login_E_Err_LoginInfoNotMatch S2C_Login_E_ErrReason = 3
	///验证通过,允许登陆,但登陆地点异常警告
	S2C_Login_E_Err_LocationWarn S2C_Login_E_ErrReason = 4
	///用户不存在
	S2C_Login_E_Err_UserNotExist S2C_Login_E_ErrReason = 5
	///已登陆
	S2C_Login_E_Err_AlreadyLogin S2C_Login_E_ErrReason = 6
	///其它错误
	S2C_Login_E_Err_Unknown S2C_Login_E_ErrReason = 7
	///客户端版本过低
	S2C_Login_E_Err_LowVersion S2C_Login_E_ErrReason = 8
)

var S2C_Login_E_ErrReason_name = map[int32]string{
	0: "E_ErrReason_",
	1: "E_Err_LoginSuccess",
	2: "E_Err_NewAccount",
	3: "E_Err_LoginInfoNotMatch",
	4: "E_Err_LocationWarn",
	5: "E_Err_UserNotExist",
	6: "E_Err_AlreadyLogin",
	7: "E_Err_Unknown",
	8: "E_Err_LowVersion",
}

var S2C_Login_E_ErrReason_value = map[string]int32{
	"E_ErrReason_":            0,
	"E_Err_LoginSuccess":      1,
	"E_Err_NewAccount":        2,
	"E_Err_LoginInfoNotMatch": 3,
	"E_Err_LocationWarn":      4,
	"E_Err_UserNotExist":      5,
	"E_Err_AlreadyLogin":      6,
	"E_Err_Unknown":           7,
	"E_Err_LowVersion":        8,
}

func (x S2C_Login_E_ErrReason) String() string {
	return proto.EnumName(S2C_Login_E_ErrReason_name, int32(x))
}

func (S2C_Login_E_ErrReason) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_a77d98885c0f92eb, []int{1, 0}
}

///登陆请求
//@msg
type C2S_Login struct {
	///微信登陆时是微信uid,游客登陆时是手机唯一标识
	UID string `protobuf:"bytes,1,opt,name=UID,proto3" json:"UID,omitempty"`
	///用户昵称
	NickName string `protobuf:"bytes,2,opt,name=NickName,proto3" json:"NickName,omitempty"`
	///用户头像url
	AvatarURL string `protobuf:"bytes,3,opt,name=AvatarURL,proto3" json:"AvatarURL,omitempty"`
	///性别
	Sex string `protobuf:"bytes,4,opt,name=sex,proto3" json:"sex,omitempty"`
	//微信登陆传openid，游客登陆传空
	Password string `protobuf:"bytes,5,opt,name=password,proto3" json:"password,omitempty"`
	///地理位置
	Location  string                `protobuf:"bytes,6,opt,name=location,proto3" json:"location,omitempty"`
	Logintype C2S_Login_E_LoginType `protobuf:"varint,7,opt,name=logintype,proto3,enum=msg.C2S_Login_E_LoginType" json:"logintype,omitempty"`
	///客户端设备类型,1-android,2-ios,3-h5
	CltType int32 `protobuf:"varint,8,opt,name=CltType,proto3" json:"CltType,omitempty"`
}

func (m *C2S_Login) Reset()         { *m = C2S_Login{} }
func (m *C2S_Login) String() string { return proto.CompactTextString(m) }
func (*C2S_Login) ProtoMessage()    {}
func (*C2S_Login) Descriptor() ([]byte, []int) {
	return fileDescriptor_a77d98885c0f92eb, []int{0}
}
func (m *C2S_Login) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *C2S_Login) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_C2S_Login.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *C2S_Login) XXX_Merge(src proto.Message) {
	xxx_messageInfo_C2S_Login.Merge(m, src)
}
func (m *C2S_Login) XXX_Size() int {
	return m.Size()
}
func (m *C2S_Login) XXX_DiscardUnknown() {
	xxx_messageInfo_C2S_Login.DiscardUnknown(m)
}

var xxx_messageInfo_C2S_Login proto.InternalMessageInfo

func (m *C2S_Login) GetUID() string {
	if m != nil {
		return m.UID
	}
	return ""
}

func (m *C2S_Login) GetNickName() string {
	if m != nil {
		return m.NickName
	}
	return ""
}

func (m *C2S_Login) GetAvatarURL() string {
	if m != nil {
		return m.AvatarURL
	}
	return ""
}

func (m *C2S_Login) GetSex() string {
	if m != nil {
		return m.Sex
	}
	return ""
}

func (m *C2S_Login) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *C2S_Login) GetLocation() string {
	if m != nil {
		return m.Location
	}
	return ""
}

func (m *C2S_Login) GetLogintype() C2S_Login_E_LoginType {
	if m != nil {
		return m.Logintype
	}
	return C2S_Login_E_LoginType_WeChat
}

func (m *C2S_Login) GetCltType() int32 {
	if m != nil {
		return m.CltType
	}
	return 0
}

///登陆回复
//@msg
type S2C_Login struct {
	Reason S2C_Login_E_ErrReason `protobuf:"varint,1,opt,name=reason,proto3,enum=msg.S2C_Login_E_ErrReason" json:"reason,omitempty"`
}

func (m *S2C_Login) Reset()         { *m = S2C_Login{} }
func (m *S2C_Login) String() string { return proto.CompactTextString(m) }
func (*S2C_Login) ProtoMessage()    {}
func (*S2C_Login) Descriptor() ([]byte, []int) {
	return fileDescriptor_a77d98885c0f92eb, []int{1}
}
func (m *S2C_Login) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *S2C_Login) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_S2C_Login.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *S2C_Login) XXX_Merge(src proto.Message) {
	xxx_messageInfo_S2C_Login.Merge(m, src)
}
func (m *S2C_Login) XXX_Size() int {
	return m.Size()
}
func (m *S2C_Login) XXX_DiscardUnknown() {
	xxx_messageInfo_S2C_Login.DiscardUnknown(m)
}

var xxx_messageInfo_S2C_Login proto.InternalMessageInfo

func (m *S2C_Login) GetReason() S2C_Login_E_ErrReason {
	if m != nil {
		return m.Reason
	}
	return S2C_Login_E_ErrReason_
}

///登陆成功后下发信息
//@msg
type S2C_LoginInfo struct {
	///玩家id
	ID int64 `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	///用户昵称
	NickName string `protobuf:"bytes,2,opt,name=NickName,proto3" json:"NickName,omitempty"`
	///头像url
	AvatarURL string `protobuf:"bytes,3,opt,name=AvatarURL,proto3" json:"AvatarURL,omitempty"`
	///货币信息
	Monies []*Money `protobuf:"bytes,4,rep,name=Monies,proto3" json:"Monies,omitempty"`
	///今日是否已签到
	DaySigned bool `protobuf:"varint,5,opt,name=DaySigned,proto3" json:"DaySigned,omitempty"`
	///已签到天数
	SignedDays int32 `protobuf:"varint,6,opt,name=SignedDays,proto3" json:"SignedDays,omitempty"`
	///每日签到奖励,数组第几个代表第几天
	SignRewards []*Item `protobuf:"bytes,7,rep,name=SignRewards,proto3" json:"SignRewards,omitempty"`
	///大厅角色性别,0-女,1-男
	HallRoleSex int32 `protobuf:"varint,9,opt,name=HallRoleSex,proto3" json:"HallRoleSex,omitempty"`
	///是否在游戏中(重连)
	InTheGame bool `protobuf:"varint,10,opt,name=InTheGame,proto3" json:"InTheGame,omitempty"`
}

func (m *S2C_LoginInfo) Reset()         { *m = S2C_LoginInfo{} }
func (m *S2C_LoginInfo) String() string { return proto.CompactTextString(m) }
func (*S2C_LoginInfo) ProtoMessage()    {}
func (*S2C_LoginInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_a77d98885c0f92eb, []int{2}
}
func (m *S2C_LoginInfo) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *S2C_LoginInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_S2C_LoginInfo.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *S2C_LoginInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_S2C_LoginInfo.Merge(m, src)
}
func (m *S2C_LoginInfo) XXX_Size() int {
	return m.Size()
}
func (m *S2C_LoginInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_S2C_LoginInfo.DiscardUnknown(m)
}

var xxx_messageInfo_S2C_LoginInfo proto.InternalMessageInfo

func (m *S2C_LoginInfo) GetID() int64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *S2C_LoginInfo) GetNickName() string {
	if m != nil {
		return m.NickName
	}
	return ""
}

func (m *S2C_LoginInfo) GetAvatarURL() string {
	if m != nil {
		return m.AvatarURL
	}
	return ""
}

func (m *S2C_LoginInfo) GetMonies() []*Money {
	if m != nil {
		return m.Monies
	}
	return nil
}

func (m *S2C_LoginInfo) GetDaySigned() bool {
	if m != nil {
		return m.DaySigned
	}
	return false
}

func (m *S2C_LoginInfo) GetSignedDays() int32 {
	if m != nil {
		return m.SignedDays
	}
	return 0
}

func (m *S2C_LoginInfo) GetSignRewards() []*Item {
	if m != nil {
		return m.SignRewards
	}
	return nil
}

func (m *S2C_LoginInfo) GetHallRoleSex() int32 {
	if m != nil {
		return m.HallRoleSex
	}
	return 0
}

func (m *S2C_LoginInfo) GetInTheGame() bool {
	if m != nil {
		return m.InTheGame
	}
	return false
}

func init() {
	proto.RegisterEnum("msg.C2S_Login_E_LoginType", C2S_Login_E_LoginType_name, C2S_Login_E_LoginType_value)
	proto.RegisterEnum("msg.S2C_Login_E_ErrReason", S2C_Login_E_ErrReason_name, S2C_Login_E_ErrReason_value)
	proto.RegisterType((*C2S_Login)(nil), "msg.C2S_Login")
	proto.RegisterType((*S2C_Login)(nil), "msg.S2C_Login")
	proto.RegisterType((*S2C_LoginInfo)(nil), "msg.S2C_LoginInfo")
}

func init() { proto.RegisterFile("Hall.proto", fileDescriptor_a77d98885c0f92eb) }

var fileDescriptor_a77d98885c0f92eb = []byte{
	// 558 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x93, 0xbf, 0x6e, 0xdb, 0x3c,
	0x14, 0xc5, 0x2d, 0x39, 0xfe, 0xa3, 0xeb, 0x2f, 0x01, 0x43, 0x7c, 0x6d, 0x09, 0xb7, 0x10, 0x0c,
	0x4d, 0x06, 0x0a, 0x78, 0x70, 0x97, 0x0e, 0x5d, 0x52, 0xc7, 0x48, 0x0d, 0x24, 0x1e, 0xe8, 0xa4,
	0x19, 0x0d, 0x56, 0x61, 0x1d, 0x21, 0x12, 0x69, 0x90, 0x4c, 0x6d, 0xbd, 0x45, 0x5f, 0xa0, 0x7b,
	0xf7, 0xbe, 0x44, 0xc7, 0x8c, 0x05, 0xba, 0x14, 0xc9, 0x8b, 0x14, 0x14, 0x6d, 0x49, 0x7b, 0x27,
	0xf3, 0xfc, 0xee, 0xf5, 0xd1, 0xe1, 0xc5, 0x25, 0xc0, 0x07, 0x96, 0xa6, 0xa3, 0xb5, 0x92, 0x46,
	0xe2, 0x66, 0xa6, 0x57, 0xfd, 0x5e, 0x26, 0x05, 0xcf, 0x1d, 0xe9, 0x43, 0x62, 0x78, 0xe6, 0xce,
	0xd1, 0x0f, 0x1f, 0x82, 0xc9, 0x78, 0xb1, 0x3c, 0x97, 0xab, 0x44, 0x60, 0x04, 0xcd, 0xab, 0xd9,
	0x29, 0xf1, 0x06, 0xde, 0x30, 0xa0, 0xf6, 0x88, 0xfb, 0xd0, 0x9d, 0x27, 0xf1, 0xdd, 0x9c, 0x65,
	0x9c, 0xf8, 0x05, 0x2e, 0x35, 0x7e, 0x05, 0xc1, 0xc9, 0x17, 0x66, 0x98, 0xba, 0xa2, 0xe7, 0xa4,
	0x59, 0x14, 0x2b, 0x60, 0xbd, 0x34, 0xdf, 0x92, 0x03, 0xe7, 0xa5, 0xf9, 0xd6, 0x7a, 0xad, 0x99,
	0xd6, 0x1b, 0xa9, 0x6e, 0x48, 0xcb, 0x79, 0xed, 0xb5, 0xad, 0xa5, 0x32, 0x66, 0x26, 0x91, 0x82,
	0xb4, 0x5d, 0x6d, 0xaf, 0xf1, 0x5b, 0x08, 0x52, 0x1b, 0xcf, 0xe4, 0x6b, 0x4e, 0x3a, 0x03, 0x6f,
	0x78, 0x34, 0xee, 0x8f, 0x32, 0xbd, 0x1a, 0x95, 0xc1, 0x47, 0x53, 0xf7, 0x7b, 0x99, 0xaf, 0x39,
	0xad, 0x9a, 0x31, 0x81, 0xce, 0x24, 0x35, 0x96, 0x92, 0xee, 0xc0, 0x1b, 0xb6, 0xe8, 0x5e, 0x46,
	0xef, 0xa0, 0x57, 0xfb, 0x0f, 0x7e, 0x0e, 0xb8, 0x26, 0x97, 0xd7, 0x7c, 0x72, 0xcb, 0x0c, 0x6a,
	0xe0, 0x67, 0x70, 0x5c, 0xe7, 0x67, 0xf7, 0x5c, 0x1b, 0xe4, 0x45, 0xdf, 0x7c, 0x08, 0x16, 0xe3,
	0xc9, 0x6e, 0x6a, 0x63, 0x68, 0x2b, 0xce, 0xb4, 0x14, 0xc5, 0xe0, 0xf6, 0xe1, 0xca, 0xfa, 0x68,
	0xba, 0x9c, 0x2a, 0x45, 0x8b, 0x0e, 0xba, 0xeb, 0x8c, 0x7e, 0x7b, 0x36, 0x40, 0xc9, 0x31, 0x82,
	0xff, 0x6a, 0x72, 0x89, 0x1a, 0x2e, 0xd2, 0x54, 0x29, 0x67, 0xb2, 0xb8, 0x8f, 0x63, 0xae, 0x35,
	0xf2, 0xf0, 0xff, 0x80, 0x1c, 0x9f, 0xf3, 0xcd, 0x49, 0x1c, 0xcb, 0x7b, 0x61, 0x90, 0x8f, 0x5f,
	0xc2, 0x8b, 0x5a, 0xf7, 0x4c, 0x7c, 0x96, 0x73, 0x69, 0x2e, 0x98, 0x89, 0x6f, 0x51, 0xb3, 0x6e,
	0xe5, 0x46, 0x7a, 0xcd, 0x94, 0x40, 0x07, 0x15, 0xbf, 0xd2, 0x5c, 0xcd, 0xa5, 0x99, 0x6e, 0x13,
	0x6d, 0x50, 0xab, 0xe2, 0x27, 0xa9, 0xe2, 0xec, 0x26, 0x2f, 0x3c, 0x51, 0x1b, 0x1f, 0xc3, 0xe1,
	0xae, 0x5f, 0xdc, 0x09, 0xb9, 0x11, 0xa8, 0x53, 0xa5, 0x39, 0x97, 0x9b, 0x8f, 0x5c, 0xe9, 0x44,
	0x0a, 0xd4, 0x8d, 0xbe, 0xfb, 0x70, 0x58, 0xde, 0xdf, 0x86, 0xc1, 0x47, 0xe0, 0xef, 0x16, 0xab,
	0x49, 0xfd, 0x7f, 0xda, 0xab, 0x08, 0xda, 0x17, 0x52, 0x24, 0x5c, 0x93, 0x83, 0x41, 0x73, 0xd8,
	0x1b, 0x43, 0x31, 0xed, 0x0b, 0xbb, 0xdf, 0x74, 0x57, 0xb1, 0x0e, 0xa7, 0x2c, 0x5f, 0x24, 0x2b,
	0xc1, 0xdd, 0xaa, 0x75, 0x69, 0x05, 0x70, 0x08, 0xe0, 0x4e, 0xa7, 0x2c, 0xd7, 0xc5, 0xb6, 0xb5,
	0x68, 0x8d, 0xe0, 0xd7, 0xd0, 0xb3, 0x8a, 0xf2, 0x0d, 0x53, 0x37, 0x9a, 0x74, 0x8a, 0xcf, 0x04,
	0xc5, 0x67, 0x66, 0x86, 0x67, 0xb4, 0x5e, 0xc5, 0x03, 0xe8, 0xd9, 0xc7, 0x46, 0x65, 0xca, 0x17,
	0x7c, 0x4b, 0x82, 0xc2, 0xad, 0x8e, 0x6c, 0x98, 0x99, 0xb8, 0xbc, 0xe5, 0x67, 0xf6, 0xae, 0xe0,
	0xc2, 0x94, 0xe0, 0x3d, 0xf9, 0xf9, 0x18, 0x7a, 0x0f, 0x8f, 0xa1, 0xf7, 0xe7, 0x31, 0xf4, 0xbe,
	0x3e, 0x85, 0x8d, 0x87, 0xa7, 0xb0, 0xf1, 0xeb, 0x29, 0x6c, 0x7c, 0x6a, 0x17, 0x2f, 0xf4, 0xcd,
	0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x03, 0x14, 0xae, 0x75, 0xcd, 0x03, 0x00, 0x00,
}

func (m *C2S_Login) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *C2S_Login) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *C2S_Login) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.CltType != 0 {
		i = encodeVarintHall(dAtA, i, uint64(m.CltType))
		i--
		dAtA[i] = 0x40
	}
	if m.Logintype != 0 {
		i = encodeVarintHall(dAtA, i, uint64(m.Logintype))
		i--
		dAtA[i] = 0x38
	}
	if len(m.Location) > 0 {
		i -= len(m.Location)
		copy(dAtA[i:], m.Location)
		i = encodeVarintHall(dAtA, i, uint64(len(m.Location)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.Password) > 0 {
		i -= len(m.Password)
		copy(dAtA[i:], m.Password)
		i = encodeVarintHall(dAtA, i, uint64(len(m.Password)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.Sex) > 0 {
		i -= len(m.Sex)
		copy(dAtA[i:], m.Sex)
		i = encodeVarintHall(dAtA, i, uint64(len(m.Sex)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.AvatarURL) > 0 {
		i -= len(m.AvatarURL)
		copy(dAtA[i:], m.AvatarURL)
		i = encodeVarintHall(dAtA, i, uint64(len(m.AvatarURL)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.NickName) > 0 {
		i -= len(m.NickName)
		copy(dAtA[i:], m.NickName)
		i = encodeVarintHall(dAtA, i, uint64(len(m.NickName)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.UID) > 0 {
		i -= len(m.UID)
		copy(dAtA[i:], m.UID)
		i = encodeVarintHall(dAtA, i, uint64(len(m.UID)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *S2C_Login) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *S2C_Login) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *S2C_Login) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Reason != 0 {
		i = encodeVarintHall(dAtA, i, uint64(m.Reason))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *S2C_LoginInfo) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *S2C_LoginInfo) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *S2C_LoginInfo) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.InTheGame {
		i--
		if m.InTheGame {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x50
	}
	if m.HallRoleSex != 0 {
		i = encodeVarintHall(dAtA, i, uint64(m.HallRoleSex))
		i--
		dAtA[i] = 0x48
	}
	if len(m.SignRewards) > 0 {
		for iNdEx := len(m.SignRewards) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.SignRewards[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintHall(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x3a
		}
	}
	if m.SignedDays != 0 {
		i = encodeVarintHall(dAtA, i, uint64(m.SignedDays))
		i--
		dAtA[i] = 0x30
	}
	if m.DaySigned {
		i--
		if m.DaySigned {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x28
	}
	if len(m.Monies) > 0 {
		for iNdEx := len(m.Monies) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Monies[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintHall(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x22
		}
	}
	if len(m.AvatarURL) > 0 {
		i -= len(m.AvatarURL)
		copy(dAtA[i:], m.AvatarURL)
		i = encodeVarintHall(dAtA, i, uint64(len(m.AvatarURL)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.NickName) > 0 {
		i -= len(m.NickName)
		copy(dAtA[i:], m.NickName)
		i = encodeVarintHall(dAtA, i, uint64(len(m.NickName)))
		i--
		dAtA[i] = 0x12
	}
	if m.ID != 0 {
		i = encodeVarintHall(dAtA, i, uint64(m.ID))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintHall(dAtA []byte, offset int, v uint64) int {
	offset -= sovHall(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *C2S_Login) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.UID)
	if l > 0 {
		n += 1 + l + sovHall(uint64(l))
	}
	l = len(m.NickName)
	if l > 0 {
		n += 1 + l + sovHall(uint64(l))
	}
	l = len(m.AvatarURL)
	if l > 0 {
		n += 1 + l + sovHall(uint64(l))
	}
	l = len(m.Sex)
	if l > 0 {
		n += 1 + l + sovHall(uint64(l))
	}
	l = len(m.Password)
	if l > 0 {
		n += 1 + l + sovHall(uint64(l))
	}
	l = len(m.Location)
	if l > 0 {
		n += 1 + l + sovHall(uint64(l))
	}
	if m.Logintype != 0 {
		n += 1 + sovHall(uint64(m.Logintype))
	}
	if m.CltType != 0 {
		n += 1 + sovHall(uint64(m.CltType))
	}
	return n
}

func (m *S2C_Login) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Reason != 0 {
		n += 1 + sovHall(uint64(m.Reason))
	}
	return n
}

func (m *S2C_LoginInfo) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.ID != 0 {
		n += 1 + sovHall(uint64(m.ID))
	}
	l = len(m.NickName)
	if l > 0 {
		n += 1 + l + sovHall(uint64(l))
	}
	l = len(m.AvatarURL)
	if l > 0 {
		n += 1 + l + sovHall(uint64(l))
	}
	if len(m.Monies) > 0 {
		for _, e := range m.Monies {
			l = e.Size()
			n += 1 + l + sovHall(uint64(l))
		}
	}
	if m.DaySigned {
		n += 2
	}
	if m.SignedDays != 0 {
		n += 1 + sovHall(uint64(m.SignedDays))
	}
	if len(m.SignRewards) > 0 {
		for _, e := range m.SignRewards {
			l = e.Size()
			n += 1 + l + sovHall(uint64(l))
		}
	}
	if m.HallRoleSex != 0 {
		n += 1 + sovHall(uint64(m.HallRoleSex))
	}
	if m.InTheGame {
		n += 2
	}
	return n
}

func sovHall(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozHall(x uint64) (n int) {
	return sovHall(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *C2S_Login) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowHall
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: C2S_Login: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: C2S_Login: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowHall
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthHall
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthHall
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.UID = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NickName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowHall
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthHall
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthHall
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.NickName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AvatarURL", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowHall
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthHall
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthHall
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AvatarURL = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Sex", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowHall
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthHall
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthHall
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Sex = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Password", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowHall
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthHall
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthHall
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Password = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Location", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowHall
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthHall
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthHall
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Location = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Logintype", wireType)
			}
			m.Logintype = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowHall
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Logintype |= C2S_Login_E_LoginType(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CltType", wireType)
			}
			m.CltType = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowHall
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CltType |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipHall(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthHall
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthHall
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *S2C_Login) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowHall
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: S2C_Login: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: S2C_Login: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Reason", wireType)
			}
			m.Reason = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowHall
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Reason |= S2C_Login_E_ErrReason(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipHall(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthHall
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthHall
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *S2C_LoginInfo) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowHall
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: S2C_LoginInfo: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: S2C_LoginInfo: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ID", wireType)
			}
			m.ID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowHall
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ID |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NickName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowHall
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthHall
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthHall
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.NickName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AvatarURL", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowHall
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthHall
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthHall
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AvatarURL = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Monies", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowHall
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthHall
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthHall
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Monies = append(m.Monies, &Money{})
			if err := m.Monies[len(m.Monies)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DaySigned", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowHall
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.DaySigned = bool(v != 0)
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SignedDays", wireType)
			}
			m.SignedDays = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowHall
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SignedDays |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SignRewards", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowHall
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthHall
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthHall
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SignRewards = append(m.SignRewards, &Item{})
			if err := m.SignRewards[len(m.SignRewards)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field HallRoleSex", wireType)
			}
			m.HallRoleSex = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowHall
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.HallRoleSex |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 10:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field InTheGame", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowHall
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.InTheGame = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipHall(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthHall
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthHall
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipHall(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowHall
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowHall
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowHall
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthHall
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupHall
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthHall
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthHall        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowHall          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupHall = fmt.Errorf("proto: unexpected end of group")
)
